웹소켓 채팅 프로토타입 구현
supershy42/chat pull request #1
Opened 2024-11-23 06:41 UTC by AhnJoonSung

## 주요 구현 사항
### 프로젝트 설정
- 깃, 프로젝트 세팅
- app 생성
- migration
- requirements.txt 작성
- WebSocket을 위한 ASGI 설정

### 기능
- chat consumer 구현
- chatroom model 작성
- chatroom create serializer 구현
- chatroom create API view 작성
- chat services 작성
- WebSocket을 통한 채팅 구현

웹 소켓 연결 요청을 수락하고, 채팅 메시지를 받아서 클라이언트에게 json 형태로 전송

---
### 2024.11.27 추가 수정 사항
- ChatRoom model에서 <user1, user2>에 대한 unique 조건 추가
- 자잘한 버그 수정
- 비즈니스 로직 service 계층으로 분리
- ChatRoom 데이터 생성 관련 테스트 코드 추가
- WebSocket 메시지 전송 및 응답 테스트 코드 추가

### 추가 고려사항
현재는 그냥 채팅방 연결 요청을 받는데, 
jwt 인증을 통해 검증된 user_id를 받아와 해당 유저가 채팅방 소속인지 검증하는 로직 추가 필요함

2024-12-07 11:16 UTC, KRimwoo approved these changes

2024-12-07 13:10 UTC, eajnoeyeel requested changes

2024-12-07 13:10 UTC, eajnoeyeel commented on chat_app/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
이 부분은 나중에 데이터베이스 검색 최적화를 위해 인덱싱이 필요할 수도 있을 것 같아요!

- “사용자가 포함된 채팅방 검색”을 위한 `user1_id`와 `user2_id`에 단일 컬럼 인덱스
예)
```
class ChatRoom(models.Model):
    user1_id = models.IntegerField(db_index=True)  # 단일 인덱스
    user2_id = models.IntegerField(db_index=True)  # 단일 인덱스
```

2024-12-07 17:12 UTC, AhnJoonSung commented on chat_app/services.py
> +def is_valid_user(user_id):
요건 저의 mistake

2024-12-07 17:28 UTC, AhnJoonSung commented on chat_app/services.py
> +    return None
넵 이후 PR에서 다 비동기로 통일했습니다.

2024-12-07 17:34 UTC, AhnJoonSung commented on chat_app/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
음 메모

2024-12-09 14:17 UTC, eajnoeyeel approved these changes
따봉따봉

2024-12-09 14:17 UTC, merged

2024-12-09 14:31 UTC, bean-baek reviewed
👌